POST http://localhost:3003/api/blogs 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lMSIsImlkIjoiNjdiNTIyMzg0MmQ2OGU0MzRhZjM1MjQwIiwiaWF0IjoxNzQwNDcxMTE3LCJleHAiOjE3NDA0NzQ3MTd9.e-JNhBUNuKfLLgt-d52yOxoaRNF1XzpTHvUgNKUR1A8

{
    "title": "tokenRefactor works",
    "author": "konstant",
    "url": "thisisurl.com",
    "likes": 14
}